apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: max-question-web
  namespace: default
spec:
  selector:
    matchLabels:
      alttag: max-question-web
      run: max-web
  template:
    metadata:
      labels:
        run: max-web
        alttag: max-question-web
    spec:
      containers:
      - image: gcr.io/wpc-chatbot/max-question-answering-web-app:latest
        imagePullPolicy: IfNotPresent
        name: max-question-web
        ports:
        - containerPort: 8000
          protocol: TCP
          name: question-port
        livenessProbe:
          httpGet:
            path: /questions/status
            port: question-port
          failureThreshold: 10
          periodSeconds: 10
          timeoutSeconds: 30
